### ISSUE TITLE
CC & Encounter tab should be not functional in Nurse Dona's log in

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#29]
CC & ENCOUNTER Tabs should be gray out for Nurse Donna's Log in
tested in site 3 : http://chartdoc-001-site3.dtempurl.com/
page url : http://chartdoc-001-site3.dtempurl.com/patient-profile?id=2380

![image](https://user-images.githubusercontent.com/75855456/102951788-ade2dd80-44f3-11eb-8b7a-178553a4debb.png)
![image](https://user-images.githubusercontent.com/75855456/102952018-28136200-44f4-11eb-952b-167db148bde5.png)

**Comment by ashimWizz** [comment]
updated
