### ISSUE TITLE
Not able to select existing patient for booking an appointment

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#3]
There is no provision to select a patient for booking an appointment. 
Path -> Doctor Schedule -> Double Click -> open schedule appointment window -> click on search ->

![Error 1](https://user-images.githubusercontent.com/75855456/101940765-fbff0380-3c0c-11eb-9e55-eceb3e2a7072.JPG)

**Comment by probaldg** [comment]
Please mention the User Name for which you have logged in to execute this test case
