### ISSUE TITLE
Incorrect Patient Profile Pictures

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#30]
Tested in Site 3 : http://chartdoc-001-site3.dtempurl.com/
Patient profile picture is not correct. It took Dr. Polimoni's picture
![image](https://user-images.githubusercontent.com/75855456/102952191-98ba7e80-44f4-11eb-8478-9d2433a8c184.png)

**Comment by ashimWizz** [comment]
Updated
