### ISSUE TITLE
Log out by single click on Question mark and Profile picture

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#31]
Log out by single click on Question mark and Profile picture

tested in site 3 : http://chartdoc-001-site3.dtempurl.com/

![image](https://user-images.githubusercontent.com/75855456/102952354-fc44ac00-44f4-11eb-8df6-b0bcd2d0e8bc.png)

**Comment by ashimWizz** [comment]
Re-assigning to Sangeet

**Comment by Swapnadeep-test** [comment]
solved
