### ISSUE TITLE
Chief Complaint is not working in Doctor's Log in

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#32]
Chief complaint is not functional in Dr. Polimoni's Login.
Tested in Site 3 : http://chartdoc-001-site3.dtempurl.com/
Page Url : http://chartdoc-001-site3.dtempurl.com/patient-profile?id=2380

![image](https://user-images.githubusercontent.com/75855456/102952837-0dda8380-44f6-11eb-825a-84bdea2ecf0a.png)

**Comment by ashimWizz** [comment]
Need details if this could be edited like the encounter tab. There is no SAVE btn mentioned in the GUI to support that.
