### ISSUE TITLE
Load Previous encounter in Doctor's Log in is not working

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#33]
Load Previous encounter in Doctor's Log in is not working
Tested in Site 3
Patient -> Encounter -> Previous Encounter

![image](https://user-images.githubusercontent.com/75855456/102953017-690c7600-44f6-11eb-954f-627eca81bb5d.png)

**Comment by ashimWizz** [comment]
@Swapnadeep-test updated in development
