### ISSUE TITLE
Patient List is not coming in Patient search

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#36]
No patient found in Patient Search. I have to put the particular patient's name in the search bar. Patient list is not coming.
URL : http://chartdoc-001-site3.dtempurl.com/patient-search-appointment?id=1

![image](https://user-images.githubusercontent.com/75855456/103185171-3640f400-48e1-11eb-8ce0-74368dcb355e.png)

**Comment by sangeet003** [comment]
Page Breaks when we enter something in search bar & press enter.

**Comment by Swapnadeep-test** [comment]
solved according to the design architecture.
