### ISSUE TITLE
When selecting date of birth in minor form the form switches to normal patient form

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#37]

**Comment by sangeet003** [comment]
Race Field missing

**Comment by Swapnadeep-test** [comment]
![image](https://user-images.githubusercontent.com/75855456/103260501-e4bd6580-49c3-11eb-8a34-c1edc70a4d27.png)

**Comment by Swapnadeep-test** [comment]
Fields for Guardian First Name is not present

![image](https://user-images.githubusercontent.com/75855456/103433398-4d038580-4c16-11eb-98b5-489c1269bf1b.png)
