### ISSUE TITLE
Newly added data is not showing in specialty master

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#39]
Operation showing successful but newly added data is not showing in specialty master.
URL : http://chartdoc-001-site3.dtempurl.com/app-specialty

![image](https://user-images.githubusercontent.com/75855456/103185350-080fe400-48e2-11eb-9fa8-40842718fea8.png)

**Comment by sangeet003** [comment]
After saving data, New data is retrieved but not reflecting in angular.
Probably need to re-assign value in array properly...

**Comment by Swapnadeep-test** [comment]
Grid pagination is not working

**Comment by Swapnadeep-test** [comment]
solved. tested successfully
