### ISSUE TITLE
Delete & Edit button is not working in the newly added field in Claim Field Master

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#40]
Delete & Edit button is not working in the newly added field in Claim Field Master.
URL : http://chartdoc-001-site3.dtempurl.com/app-claim-field-master
![image](https://user-images.githubusercontent.com/75855456/103185401-4dccac80-48e2-11eb-865a-9c9f826c1521.png)

**Comment by sangeet003** [comment]
API Returns:
The DELETE statement conflicted with the REFERENCE constraint "FK_T_CLAIM_FIELDS_DETAILS_T_CLAIM_FIELDS_HEADER". The conflict occurred in database "ChartDoc-Billing-V2", table "dbo.T_CLAIM_FIELDS_DETAILS", column 'FIELDID'.
