### ISSUE TITLE
No save button is available in CC for Dr.Polimeni's log in

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#45]
![image](https://user-images.githubusercontent.com/75855456/103263496-0facb700-49ce-11eb-9419-5306ae54e6a0.png)

**Comment by ashimWizz** [comment]
No Save button in design. Require **approval from Craig** with functionality. Already communicated this point.

**Comment by Swapnadeep-test** [comment]
Solved
