### ISSUE TITLE
CPT is not generating the charge amount in Billing

### ISSUE THREAD

**Issue by Swapnadeep-test** [probaldg/chartdoc#55]
![image](https://user-images.githubusercontent.com/75855456/103433269-80451500-4c14-11eb-9c72-4674aa746e26.png)

**Comment by ashimWizz** [comment]
New item for development. @suvreshchatterjee: let know if it requires to be addressed by Wizard team.

**Comment by probaldg** [comment]
@ashimWizz 
Hi Ashim, please address it with Wizard team.

**Comment by Swapnadeep-test** [comment]
charge amount is coming
